version: '3.8'
name: spacetraders-again
services:
  app:
    depends_on:
      - redis
      - influxdb
      - seq
    image: spacetradersagain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REDIS_HOST: redis
      SEQ_HOST: seq
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: '${INFLUX_TOKEN}'
      INFLUX_ORG: my-org
      INFLUX_BUCKET: my-bucket
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      PURCHASE_MINING_SHIPS: 10
      PURCHASE_SHUTTLES: 0
      PURCHASE_HAULERS: 5
      SHOULD_MINE: true
      TZ: 'Australia/Sydney'
    ports:
      - 3000:3000
    command: npm start -- start
    profiles: ['prod']
    restart: unless-stopped
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - '3001:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'

  seq:
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=local
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_PASSWORD}
    volumes:
      - $PWD/data/seq:/data
    ports:
      - 5341:80
    image: datalust/seq
  postgres:
    image: postgres:15
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

  adminer:
    build:
      dockerfile_inline: |
        FROM adminer
        ADD --chmod=644 https://raw.githubusercontent.com/staff0rd/adminer-plugins/master/AdminerJsonPreview.php /var/www/html/plugins/AdminerJsonPreview.php
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADMINER_PLUGINS: 'AdminerJsonPreview'

volumes:
  grafana_storage: {}
