version: '3.8'
name: spacetraders-again
services:
  influxdb:
    ports:
      - 8086:8086
    volumes:
      - $PWD/data/influx-data:/var/lib/influxdb2
      - $PWD/data/influx-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    image: influxdb:2
    restart: unless-stopped
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - '3001:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
  redis:
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'redis_storage:/data'
  redis-commander:
    depends_on:
      - redis
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379 # note: this has to be the port the redis container exposes.
    ports:
      - '8081:8081'
volumes:
  grafana_storage: {}
  redis_storage: {}
