version: '3.8'
name: spacetraders-again
services:
  app:
    depends_on:
      - redis
      - influxdb
      - seq
    image: spacetradersagain
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      REDIS_HOST: redis
      SEQ_HOST: seq
      INFLUX_URL: http://influxdb:8086
      INFLUX_TOKEN: '${INFLUX_TOKEN}'
      INFLUX_ORG: my-org
      INFLUX_BUCKET: my-bucket
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      PURCHASE_MINING_SHIPS: 5
      PURCHASE_SHUTTLES: 0
      PURCHASE_SATELITES: 0
      SHOULD_MINE: true
      TZ: 'Australia/Sydney'
    ports:
      - 3000:3000
    command: npm start -- start
    profiles: ['prod']
    restart: unless-stopped
  influxdb:
    ports:
      - 8086:8086
    volumes:
      - $PWD/data/influx-data:/var/lib/influxdb2
      - $PWD/data/influx-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=my-user
      - DOCKER_INFLUXDB_INIT_PASSWORD=my-password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    image: influxdb:2
    restart: unless-stopped
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    environment:
      # increases the log level from info to debug
      - GF_LOG_LEVEL=debug
    ports:
      - '3001:3000'
    volumes:
      - 'grafana_storage:/var/lib/grafana'
  redis:
    hostname: redis
    image: redis:alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - 'redis_storage:/data'
  redis-commander:
    depends_on:
      - redis
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379 # note: this has to be the port the redis container exposes.
    ports:
      - '8081:8081'
  seq:
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=stafford
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=${SEQ_PASSWORD}
    volumes:
      - $PWD/data/seq:/data
    ports:
      - 5341:80
    image: datalust/seq
  postgres:
    image: postgres:15
    ports:
      - '${POSTGRES_PORT}:5432'
    restart: unless-stopped
    volumes:
      - $PWD/data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'

  adminer:
    build:
      dockerfile_inline: |
        FROM adminer
        ADD --chmod=644 https://raw.githubusercontent.com/staff0rd/adminer-plugins/master/AdminerJsonPreview.php /var/www/html/plugins/AdminerJsonPreview.php
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADMINER_PLUGINS: 'AdminerJsonPreview'

volumes:
  grafana_storage: {}
  redis_storage: {}
